### PR TITLE
RAR files extract support 

### PR DESCRIPTION
**Pull request by ratmole**
it seems that RAR Subtitle extraction is not possible anymore with xbmc.
With this PR you can extract RAR files with python-rarfile Module.

### CODE REVIEW

**Comment by Twilight0** [comment]
Instructions given apply to Linux based systems, so for those who 're using other platforms must have a way of importing rarfile module. I will try to include it inside the addon or import existing Kodi addon from respective libraries, then tweak your pull request accordingly.

Thank you very much for your contribution.

**Comment by ratmole** [comment]
Forgot about other Platforms. it should be ok now.

**Comment by Twilight0** [comment]
Rarfile expects unrar binary to be in PATH. Linux systems are ok with python-rarfile, Windows can have unrar command line utility, but it must be set in PATH. I am not sure enough about Android.

**Comment by Twilight0** [comment]
I adjusted your pull request accordingly in a new branch for testing purposes. As soon as I ensure a way of seamless operation on Android systems, I will merge the branch into master.

**Comment by Twilight0** [comment]
I am seriously considering using an online service for rar extraction because there is NO seamless integration on all platforms. RAR is a proprietary library and it hasn't seen wide adoption.

**Comment by Twilight0** [comment]
I ended up using rar:// Kodi native filesystem-like implementation which appears to be platform independent.

**Comment by ratmole** [comment]
saw it to... good news.

**Pull request closed without merging**
